[general]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#ffcc00"
text = "#000000"

[colors.primary]
background = "#1d1f20"
foreground = "#72777b"

[colors.normal]
black = "#72777b"
blue = "#9992f0"
cyan = "#6caeff"
green = "#64d38a"
magenta = "#bf74d2"
red = "#ff8b92"
white = "#f2f2f2"
yellow = "#f3d58b"

[colors.bright]
black = "#72777b"
blue = "#9992f0"
cyan = "#6caeff"
green = "#64d38a"
magenta = "#bf74d2"
red = "#ff8b92"
white = "#f2f2f2"
yellow = "#f3d58b"

[cursor]
style.shape = "Block"
style.blinking = "Off"
unfocused_hollow = true

[font]
size = 13.0
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 0 }
normal = { family = "Iosevka Term SS12", style = "Regular" }
bold = { style = "Regular" }
italic = { style = "Regular" }

[[hints.enabled]]
command = "open"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
binding = { key = "U", mods = "Command|Shift" }
mouse = { enabled = true, mods = "Command|Shift" }

[keyboard]
bindings = [
  { chars = "\u0004", key = "D", mods = "Command" },
  { chars = "\u0014", key = "T", mods = "Command" },
  { chars = "\u0018", key = "W", mods = "Command" },
]

[mouse]
hide_when_typing = false
bindings = [{ action = "PasteSelection", mouse = "Middle" }]

[scrolling]
history = 10000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
padding = { x = 0, y = 0 }

# -- dotenv theme
# [colors.primary]
# background = "#2b0540"
# foreground = "#d65ce8"
# [colors.normal]
# black = "#72777b"
# blue = "#6364ff"
# cyan = "#55acee"
# green = "#71b59c"
# magenta = "#eba5ff"
# red = "#ff8b8b"
# white = "#ffffff"
# yellow = "#f3d58b"
# [colors.bright]
# black = "#72777b"
# blue = "#6364ff"
# cyan = "#55acee"
# green = "#71b59c"
# magenta = "#eba5ff"
# red = "#ff8b8b"
# white = "#ffffff"
# yellow = "#f3d58b"

# -- everforest dark theme
# [colors.primary]
# background = "#2d353b"
# foreground = "#d3c6aa"
# [colors.normal]
# black = "#475258"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# [colors.bright]
# black = "#475258"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"

# -- flare theme
# [colors.primary]
# background = "#1d1f20"
# foreground = "#72777b"
# [colors.normal]
# black = "#72777b"
# blue = "#9992f0"
# cyan = "#6caeff"
# green = "#64d38a"
# magenta = "#bf74d2"
# red = "#ff8b92"
# white = "#f2f2f2"
# yellow = "#f3d58b"
# [colors.bright]
# black = "#72777b"
# blue = "#9992f0"
# cyan = "#6caeff"
# green = "#64d38a"
# magenta = "#bf74d2"
# red = "#ff8b92"
# white = "#f2f2f2"
# yellow = "#f3d58b"

# -- ps theme
# [colors.primary]
# background = "#292d3e"
# foreground = "#959dcb"
# [colors.normal]
# black = "#292d3e"
# blue = "#82aaff"
# cyan = "#89ddff"
# green = "#c3e88d"
# magenta = "#c792ea"
# red = "#f07178"
# white = "#d0d0d0"
# yellow = "#ffcb6b"
# [colors.bright]
# black = "#434758"
# blue = "#9cc4ff"
# cyan = "#a3f7ff"
# green = "#ddffa7"
# magenta = "#e1acff"
# red = "#ff8b92"
# white = "#ffffff"
# yellow = "#ffe585"
